Extensions + FIFO rate limiting implementation
raisely/restcore pull request #20
Opened 2020-09-22 04:21 UTC by flynnham

* Added limited API for extending Restie and core functionality without interfering with essential internals
* Added FIFO queueing implementation to provide rate limiting
* Re-enabled disabled batching test
* Fixed missing mocha definition from eslint
* Updated dependencies

2020-09-22 04:22 UTC, flynnham commented
This still needs plugin validation logic added, though that seems tentative.

2020-09-27 19:42 UTC, chrisjensen approved these changes

2020-09-27 20:02 UTC, chrisjensen requested changes
There's some problems with the queuing mechanism that will lead to repeated requests and exceeding the bucket size

2020-09-27 20:02 UTC, chrisjensen commented on src/plugins/limiter.js
> +		let current = queued.shift();
This is a stack (LIFO) not FIFO. Tasks are being added to the start of the array below, and this is pulling the first element

2020-09-27 20:02 UTC, chrisjensen commented on src/plugins/limiter.js
> +			if (overloadTimeout) clearTimeout(overloadTimeout);
This is unnecessary - it's cleared at the top of the function and there's no await since then

2020-09-27 20:02 UTC, chrisjensen commented on src/plugins/limiter.js
> +			await Promise.all(currentBatch.map(task => task()));
If one of these promises takes a long time, it will block the queue.
We should be using `Promise.race()` or similar

2020-09-27 20:02 UTC, chrisjensen commented on src/plugins/limiter.js
> +				currentBatchPromiseRef = startBatching();
This could lead to multiple startBatching calls running concurrently which will in turn lead to requests being duplicated.
eg
If my bucketGroupingWindow is 5ms
I push 11 promises, the last call will setup a timeout for 5ms
At 5ms it runs and goes into the while loop and awaits all 10 to finish
At 6m I push another promise, the timeout is cleared (but it's already run) and queues another timeout
At 11ms that timeout runs `startBatching` again which will add the 11th task to the queue and then call `performCurrentBatch` and *start a second copy of promises 1 through to 10*

2020-09-27 20:02 UTC, chrisjensen commented on src/plugin.js
> +			console.warn('A Restie plugin altered fetching without returning a function. This will likely cause issues', {
I think you can safely remove `likely` 
The next statement in the console logs will definitely be an exception 😂

2021-01-18 16:27 UTC, closed without merging